### ISSUE TITLE
Inventory File and Swarm-iface Variable

### ISSUE THREAD

**Issue by nischay30** [nextrevision/ansible-swarm-playbook#1]
Hey tell me what is the syntax in which you want the Inventory File and how to override the Swarm-iface variable.
give me some examples with some randoms hosts

thanks

**Comment by nextrevision** [comment]
The inventory follows ansible's standard inventory scheme (http://docs.ansible.com/ansible/intro_inventory.html). The only assumptions I make are that you have two groups: manager and worker. An example inventory could look like:

```
[manager]
example-manager-host-1
example-manager-host-2
example-manager-host-3

[worker]
example-worker-host-1
example-worker-host-2
example-worker-host-3
```

You can override the `swarm_iface` variable in a number of places. Ansible's docs give a number of good examples on where to override variables [here](http://docs.ansible.com/ansible/playbooks_variables.html#variable-examples), but probably the quickest is via command-line using the `-e` flag (ex: `ansible-playbook -e "swarm_iface=eth300" swarm.yml`).
