### ISSUE TITLE
Issue in ansible playbook swarm.yml

### ISSUE THREAD

**Issue by himanshkumar** [nextrevision/ansible-swarm-playbook#14]
TASK [add initialized host to swarm_manager_operational group]
fatal: [manager-1]: FAILED! => {"msg": "The conditional check 'bootstrap_first_node | changed' failed. The error was: template error while templating string: no filter named 'changed'. String: {% if bootstrap_first_node | changed %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/***********/vagrant/ansible-swarm-playbook/swarm.yml': line 72, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: add initialized host to swarm_manager_operational group\n      ^ here\n"}

**Comment by wh1test** [comment]
@himanshkumar  just change this line
`when: bootstrap_first_node | changed`
to this:
`when: bootstrap_first_node.changed`
