### ISSUE TITLE
New Systems are not added in Swarm

### ISSUE THREAD

**Issue by nischay30** [nextrevision/ansible-swarm-playbook#2]
Hey,
This playbook is working only for new Setups.

But if i try to add one more system in an existing setup through this script,the system is not added in the swarm.
Check this thing.

Thanks

**Comment by nextrevision** [comment]
Which playbook are you using? If it is the `swarm.yml` playbook and not the `swarm-facts.yml` playbook, then I did see an issue in the loop which was fixed with this commit: 27ddeab09a0446eac38cf1e8d8a824e6e37b382e.

**Comment by nischay30** [comment]
Ok..I will Check this out.
Thanx
