### ISSUE TITLE
error checking ControlAvailable value

### ISSUE THREAD

**Issue by lmeyemezu** [nextrevision/ansible-swarm-playbook#3]
Hi,
using when: "{{ hostvars[item]['docker_info']['Swarm']['ControlAvailable'] }} == 'true'"
always evaluates to true even in if the node is not a master

**Comment by nextrevision** [comment]
This shouldn't affect the playbook because that condition is never being tested. Instead of checking a boolean value for it's string value, I would instead try simplifying the condition to:

```
- name: do something
  debug: msg="ControlAvailable is set to true"
  when: "{{ hostvars[item]['docker_info']['Swarm']['ControlAvailable'] }}"
```
