### ISSUE TITLE
Ansible fact 'play_hosts' deprecated in 2.2.0.0

### ISSUE THREAD

**Issue by mboggess** [nextrevision/ansible-swarm-playbook#5]
First of all, thanks for your work on this.

Second, I just ran across http://docs.ansible.com/ansible/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts which states that the Ansible fact 'play_hosts' is deprecated in 2.2. Just wanted to let you know, in the event you hadn't run across it.

**Comment by nextrevision** [comment]
Glad you like it and thanks for letting me know, I hadn't run across it yet. I'll add support for `ansible_play_hosts` instead here shortly. Thanks!
