### ISSUE TITLE
docker_info_facts doesn't support docker==2.1.0 python

### ISSUE THREAD

**Issue by DBLaci** [nextrevision/ansible-swarm-playbook#8]
Instead of docker-py newer ansible (2.3) uses docker python module (pip install docker)

The fix is almost trivial:

```
--- library/docker_info_facts.py.bak    2017-03-01 15:46:36.629676252 +0100
+++ library/docker_info_facts   2017-03-01 15:54:48.506619896 +0100
@@ -29,7 +29,7 @@
 """
 
 try:
-    from docker import Client
+    from docker import APIClient
 except:
     docker_lib_missing = True
 else:
@@ -38,8 +38,7 @@
 
 def _get_docker_info():
     try:
-        cli = Client()
-        return cli.info(), False
+        return APIClient().info(), False
     except Exception as e:
         return {}, e.message
 
@@ -57,7 +56,7 @@
     info, err = _get_docker_info()
 
     if err:
-        module.fail_json(msg=err.message)
+        module.fail_json(msg=err)
 
     module.exit_json(
         changed=True,
```

This will break docker-py I think, but maybe this is useful for others for progress.

**Comment by nextrevision** [comment]
Thanks for pointing that out and providing the diff. I added support for that in https://github.com/nextrevision/ansible-swarm-playbook/commit/96175424c158f394fb4cd26432d20e078720a32c. It worked with ansible 1.9.4 and 2.x as well as the docker-py and docker python libraries. Mind testing it out and seeing if it works for you?
